### ISSUE TITLE
Python 3.12 waiting list/status

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcds-envs#326]
I noticed that the python 3.12 list is getting pretty short

```
Found uninstallable package hklpy>=1.1.0
Found uninstallable package pmgr>=2.1.2
Found uninstallable package pyca>=3.2.0
```

All other packages on our lists are installable in python 3.12
We have not yet run any integration test at this level and we still need to resolve the issues in #205

**Comment by tangkong** [comment]
I suspect pmgr is still using versioneer, though I forget how to remove that.  Is it just removing `versioneer.py` from the `Manifest.in`?

<details><summary>install attempt</summary>
<p>

```
(pcds-5.8.4)roberttk@psbuild-rhel7-01:~$ conda activate py312
(py312)roberttk@psbuild-rhel7-01:~$ pip install pmgr
Collecting pmgr
  Downloading pmgr-2.0.2.tar.gz (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.5/82.5 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-te640hg1/pmgr_f2e201e84753464db1aaef98a5c8f4fe/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-te640hg1/pmgr_f2e201e84753464db1aaef98a5c8f4fe/setup.py", line 5, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-te640hg1/pmgr_f2e201e84753464db1aaef98a5c8f4fe/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-te640hg1/pmgr_f2e201e84753464db1aaef98a5c8f4fe/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-te640hg1/pmgr_f2e201e84753464db1aaef98a5c8f4fe/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</p>
</details>

**Comment by ZLLentz** [comment]
We can remove versioneer and do the version handling through pyproject.toml + setuptools_scm.
We can also update the versioneer file to be compatible with python 3.12.

**Comment by ZLLentz** [comment]
Ah, I see what you mean now- the file is still there when we've _already_ switched to setuptools_scm.

**Comment by ZLLentz** [comment]
One wrinkle- pmgr is currently at 2.1.2
So, why is such an old version being picked in the pip install?
Well, it's because there have been zero pypi uploads of pmgr since 2021...

**Comment by tangkong** [comment]
So the tags haven't been getting created recently huh.  We can fix that

**Comment by tangkong** [comment]
Some digging: 
https://github.com/pcdshub/pcds-ci-helpers/blob/124a96cab9871b2e8919037cf1aad712a97b0440/.github/workflows/python-pip-test.yml#L212-L213

- deploy-on-success is True, as seen in [job setup](https://github.com/pcdshub/pmgr/actions/runs/8930313174/job/24530132048#step:1:45)
- the event should be a push/tag on release, but I can't confirm this and don't see jobs from previous releases

**Comment by tangkong** [comment]
Making a new tag pushed pmgr to pypi this time.  Now we have a different issue:

<details><summary>We need to set `MYSQLCLIENT_CFLAGS` and `MYSQLCLIENT_LDFLAGS` env vars manually</summary>
<p>

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 1.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "/cds/home/r/roberttk/.conda/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/cds/home/r/roberttk/.conda/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/cds/home/r/roberttk/.conda/envs/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r2nnm4r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-r2nnm4r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-r2nnm4r4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 155, in <module>
        File "<string>", line 49, in get_config_posix
        File "<string>", line 28, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

</p>
</details> 

Do I want to do this?  Not really.  I wonder why we're not just using sqlite here?...

**Comment by ZLLentz** [comment]
is there just no equivalent mysqldb python library in python 3.12?

**Comment by tangkong** [comment]
It actually is py3.12 compatible, these env vars are just mandatory now:
https://github.com/PyMySQL/mysqlclient/discussions/624
https://github.com/PyMySQL/mysqlclient/issues/672

**Comment by ZLLentz** [comment]
ok, so we have to update pmgr to configure these?

**Comment by tangkong** [comment]
I think so.  I'm trying to figure out what our environment-specific values would be.

**Comment by tangkong** [comment]
For psbuild the following works:
```
(py312)roberttk@psbuild-rhel7-01:~/src/pmgr(master +)$ history | grep MYSQL
 8916  2024-05-02 16:58:15 $ export MYSQLCLIENT_CFLAGS=`mysql_config --cflags`
 8918  2024-05-02 17:01:13 $ export MYSQLCLIENT_LDFLAGS=`mysql_config --libs`
(py312)roberttk@psbuild-rhel7-01:~/src/pmgr(master +)$ env | grep MYSQL
MYSQLCLIENT_LDFLAGS=-L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto
MYSQLCLIENT_CFLAGS=-I/usr/include/mysql
```

The build then errors on qtpyinheritance for use of configparser's deprecated `SafeConfigParser`.  That's not us though....

Also I should have put this in pmgr but we're here now

**Comment by ZLLentz** [comment]
qtpyinheritance is actually us: https://github.com/pcdshub/qtpyinheritance

**Comment by tangkong** [comment]
OH derp I got it mixed up with the qtpy hints thing.  I'll fix that today

**Comment by tangkong** [comment]
Once we get past qtpyinheritance, all the wheels seem to build except for `mysqlclient` again.  We hit upon an issue similar to https://github.com/PyMySQL/mysqlclient/discussions/624, which was addressed by installing a latest mariadb-devel.  We don't manage these packages though correct?  

<details><summary>Details</summary>
<p>

```
  error: subprocess-exited-with-error

  × Building wheel for mysqlclient (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      # Options for building extension module:
        extra_compile_args: ['-I/usr/include/mysql', '-std=c99']
        extra_link_args: ['-L/usr/lib64/mysql', '-lmysqlclient', '-lpthread', '-lz', '-lm', '-ldl', '-lssl', '-lcrypto']
        define_macros: [('version_info', (2, 2, 4, 'final', 0)), ('__version__', '2.2.4')]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/__init__.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/_exceptions.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/connections.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/converters.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/cursors.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/release.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      copying src/MySQLdb/times.py -> build/lib.linux-x86_64-cpython-312/MySQLdb
      creating build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/CR.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/ER.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      copying src/MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-cpython-312/MySQLdb/constants
      running egg_info
      writing src/mysqlclient.egg-info/PKG-INFO
      writing dependency_links to src/mysqlclient.egg-info/dependency_links.txt
      writing top-level names to src/mysqlclient.egg-info/top_level.txt
      reading manifest file 'src/mysqlclient.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src/mysqlclient.egg-info/SOURCES.txt'
      copying src/MySQLdb/_mysql.c -> build/lib.linux-x86_64-cpython-312/MySQLdb
      running build_ext
      building 'MySQLdb._mysql' extension
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/src
      creating build/temp.linux-x86_64-cpython-312/src/MySQLdb
      gcc -pthread -B /cds/home/r/roberttk/.conda/envs/py312/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /cds/home/r/roberttk/.conda/envs/py312/include -fPIC -O2 -isystem /cds/home/r/roberttk/.conda/envs/py312/include -fPIC "-Dversion_info=(2, 2, 4, 'final', 0)" -D__version__=2.2.4 -I/cds/home/r/roberttk/.conda/envs/py312/include/python3.12 -c src/MySQLdb/_mysql.c -o build/temp.linux-x86_64-cpython-312/src/MySQLdb/_mysql.o -I/usr/include/mysql -std=c99
      src/MySQLdb/_mysql.c: In function ‘_mysql_ConnectionObject_Initialize’:
      src/MySQLdb/_mysql.c:539:44: error: ‘MYSQL_OPT_SSL_KEY’ undeclared (first use in this function)
               mysql_options(&(self->connection), MYSQL_OPT_SSL_KEY, key);
                                                  ^
      src/MySQLdb/_mysql.c:539:44: note: each undeclared identifier is reported only once for each function it appears in
      src/MySQLdb/_mysql.c:540:44: error: ‘MYSQL_OPT_SSL_CERT’ undeclared (first use in this function)
               mysql_options(&(self->connection), MYSQL_OPT_SSL_CERT, cert);
                                                  ^
      src/MySQLdb/_mysql.c:541:44: error: ‘MYSQL_OPT_SSL_CA’ undeclared (first use in this function)
               mysql_options(&(self->connection), MYSQL_OPT_SSL_CA, ca);
                                                  ^
      src/MySQLdb/_mysql.c:542:44: error: ‘MYSQL_OPT_SSL_CAPATH’ undeclared (first use in this function)
               mysql_options(&(self->connection), MYSQL_OPT_SSL_CAPATH, capath);
                                                  ^
      src/MySQLdb/_mysql.c:543:44: error: ‘MYSQL_OPT_SSL_CIPHER’ undeclared (first use in this function)
               mysql_options(&(self->connection), MYSQL_OPT_SSL_CIPHER, cipher);
                                                  ^
      src/MySQLdb/_mysql.c:556:13: warning: implicit declaration of function ‘mysql_optionsv’ [-Wimplicit-function-declaration]
                   mysql_optionsv(&(self->connection), MYSQL_OPT_SSL_ENFORCE, (void *)&enforce_tls);
                   ^
      src/MySQLdb/_mysql.c:556:49: error: ‘MYSQL_OPT_SSL_ENFORCE’ undeclared (first use in this function)
                   mysql_optionsv(&(self->connection), MYSQL_OPT_SSL_ENFORCE, (void *)&enforce_tls);
                                                       ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

```

</p>
</details>

**Comment by tangkong** [comment]
`hklpy` runs into problems during `pygobject` installation:

<details><summary>Details</summary>
<p>

```
Collecting pygobject (from hklpy)
  Downloading pygobject-3.48.2.tar.gz (715 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 715.2/715.2 kB 13.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      + meson setup /tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f /tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f/.mesonpy-l75q_imd -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=/tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f/.mesonpy-l75q_imd/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: /tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f
      Build dir: /tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f/.mesonpy-l75q_imd
      Build type: native build
      Project name: pygobject
      Project version: 3.48.2
      C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
      C linker for the host machine: cc ld.bfd 2.27-44
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python3 found: YES (/cds/home/r/roberttk/.conda/envs/py312/bin/python3.12)
      Found pkg-config: YES (/usr/bin/pkg-config) 0.27.1
      Run-time dependency python found: YES 3.12
      Dependency gobject-introspection-1.0 found: NO found 1.56.1 but need: '>= 1.64.0'
      Found CMake: /usr/bin/cmake (2.8.12.2)
      WARNING: The version of CMake /usr/bin/cmake is 2.8.12.2 but version >=3.4 is required
      Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)
      Not looking for a fallback subproject for the dependency gobject-introspection-1.0 because:
      Use of fallback dependencies is disabled.

      ../meson.build:29:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.

      A full log can be found at /tmp/pip-install-ipt200so/pygobject_7a806023c46f47bea2c6d096de43e11f/.mesonpy-l75q_imd/meson-logs/meson-log.txt
      [end of output]
```

</p>
</details> 

we have similar packages installed but not that one specifically

**Comment by tangkong** [comment]
I've updated qtpyinheritance with pyproject.toml and a conda-recipe.  Even though it's only used in typhos, removing / deprecating it would be more annoying than simply making it compatible with py3.12
https://github.com/pcdshub/qtpyinheritance/pull/5

**Comment by tangkong** [comment]
I think pyca just needs a pyproject migration and it'll be installable with py3.12

**Comment by ZLLentz** [comment]
To my eye, we are no longer waiting on anything in particular.
